bfj:
	gcc 00_bfj.c ../dft_graph.c -ggdb -o bfj.out

ufj:
	gcc 01_ufj.c ../dft_graph.c -ggdb -o ufj.out

bt:
	gcc 02_bt.c ../dft_graph.c -ggdb -o bt.out

trellis:
	gcc 03_trellis.c ../dft_graph.c -ggdb -o trellis.out

diamond:
	gcc 04_diamond.c ../dft_graph.c -ggdb -o diamond.out

clean:
	rm -rf *.out
